dummy() = return

@testset "@metal" begin
    @test_throws UndefVarError @metal undefined()
    @test_throws MethodError @metal dummy(1)
end

@testset "launch configuration" begin
    @metal dummy()

    threads = 1
    @metal threads dummy()
    @metal threads=1 dummy()
    @metal threads=(1,1) dummy()
    @metal threads=(Int32(1),Int64(1)) dummy()
    @metal threads=(1,1,1) dummy()
    @metal threads=(Int8(1),Int32(1),1) dummy()

    groups = 1
    @metal groups dummy()
    @metal groups=1 dummy()
    @metal groups=(1,1) dummy()
    @metal groups=(Int32(1),Int64(1)) dummy()
    @metal groups=(1,1,1) dummy()
    @metal groups=(Int8(1),Int32(1),1) dummy()

    @metal macos=Metal.macos_version() dummy()
    @metal metal=Metal.metal_support() dummy()
    @metal air=Metal.air_support() dummy()

    @test_throws InexactError @metal threads=(-2) dummy()
    @test_throws InexactError @metal groups=(-2) dummy()
    @test_throws ArgumentError @metal threads=(1025) dummy()
    @test_throws ArgumentError @metal threads=(1000,2) dummy()
end

@testset "launch=false" begin
    k = @metal launch=false dummy()
    k()
    k(; threads=1)

    # TODO: kernel introspection
end

@testset "inference" begin
    foo() = @metal dummy()
    @inferred foo()

    # with arguments, we call mtlconvert
    kernel(a) = return
    bar(a) = @metal kernel(a)
    @inferred bar(MtlArray([1]))
end


@testset "reflection" begin
    Metal.code_lowered(dummy, Tuple{})
    Metal.code_typed(dummy, Tuple{})
    Metal.code_warntype(devnull, dummy, Tuple{})
    Metal.code_llvm(devnull, dummy, Tuple{})
    Metal.code_air(devnull, dummy, Tuple{})

    @device_code_lowered @metal dummy()
    @device_code_typed @metal dummy()
    @device_code_warntype io=devnull @metal dummy()
    @device_code_llvm io=devnull @metal dummy()
    @device_code_air io=devnull @metal dummy()

    mktempdir() do dir
        @device_code dir=dir @metal dummy()
    end

    @test_throws ErrorException @device_code_lowered nothing

    # make sure kernel name aliases are preserved in the generated code
    @test occursin("dummy", sprint(io->(@device_code_llvm io=io optimize=false @metal dummy())))
    @test occursin("dummy", sprint(io->(@device_code_llvm io=io @metal dummy())))

    # `code_llvm` shows the IR as generated by Julia, with generic LLVM intrinsics;
    # `code_air` shows it lowered to AIR (downgraded and disassembled again)
    let
        sqrt_kernel(x) = (unsafe_store!(x, sqrt(unsafe_load(x))); return)
        llvm = sprint(io->Metal.code_llvm(io, sqrt_kernel, Tuple{Core.LLVMPtr{Float32,1}}))
        @test occursin("llvm.sqrt.f32", llvm)
        @test !occursin("air.sqrt.f32", llvm)

        air = sprint(io->Metal.code_air(io, sqrt_kernel, Tuple{Core.LLVMPtr{Float32,1}}))
        @test occursin("air.sqrt.f32", air)
        @test !occursin("llvm.sqrt.f32", air)

        # the AIR module contains kernel-related metadata
        air_mod = sprint(io->Metal.code_air(io, sqrt_kernel, Tuple{Core.LLVMPtr{Float32,1}};
                                            kernel=true, dump_module=true))
        @test occursin("air.kernel", air_mod)
        @test occursin("air.version", air_mod)
    end

    # make sure invalid kernels can be partially reflected upon
    let
        invalid_kernel() = throw()
        @test_throws Metal.InvalidIRError @metal invalid_kernel()
        @test_throws Metal.InvalidIRError @grab_output @device_code_warntype @metal invalid_kernel()
        out, err = @grab_output begin
            try
                @device_code_warntype @metal invalid_kernel()
            catch
            end
        end
        @test occursin("Body::Union{}", err)
    end

    # set name of kernel
    @test occursin("mykernel", sprint(io->(@device_code_llvm io=io begin
        @metal name="mykernel" dummy()
    end)))

    # set macOS, AIR, and Metal versions
    let
        @test occursin("""!{!"Metal", i32 3, i32 2, i32 1}""",
                       sprint(io->Metal.code_llvm(io, dummy, Tuple{}; metal=v"3.2.1",
                                                      dump_module=true, kernel=true)))

        @test occursin("!{i32 3, i32 2, i32 1}",
                       sprint(io->Metal.code_llvm(io, dummy, Tuple{}; air=v"3.2.1",
                                                      dump_module=true, kernel=true)))

        @test occursin("""!"SDK Version", [3 x i32] [i32 15, i32 2, i32 1]}""",
                       sprint(io->Metal.code_llvm(io, dummy, Tuple{}; macos=v"15.2.1",
                                                      dump_module=true, kernel=true)))

        # compatibility versions are normalized to marketing versions
        @test occursin("""!"SDK Version", [3 x i32] [i32 26, i32 2, i32 1]}""",
                       sprint(io->Metal.code_llvm(io, dummy, Tuple{}; macos=v"16.2.1",
                                                      dump_module=true, kernel=true)))

        # targeting macOS < 14, or the AIR versions that come with it, is not supported
        @test_throws "Metal.jl requires AIR 2.6" begin
            Metal.code_llvm(devnull, dummy, Tuple{}; macos=v"13")
        end
        @test_throws "Metal.jl requires AIR 2.6" begin
            Metal.code_llvm(devnull, dummy, Tuple{}; air=v"2.5")
        end
    end

    @test Metal.return_type(identity, Tuple{Int}) === Int
    @test Metal.return_type(sin, Tuple{Float32}) === Float32
    @test Metal.return_type(getindex, Tuple{MtlDeviceArray{Float32,1,1},Int32}) === Float32
    @test Metal.return_type(getindex, Tuple{Base.RefValue{Integer}}) === Integer
end



function tester(A)
    idx = thread_position_in_grid().x
    A[idx] = Int(5)
    return nothing
end

bufferSize = 8
bufferA = MtlArray{Int,1,Metal.SharedStorage}(undef, tuple(bufferSize))
vecA = unsafe_wrap(Vector{Int}, pointer(bufferA), tuple(bufferSize))

@testset "synchronization" begin
    @metal threads=(bufferSize) tester(bufferA)
    synchronize()
    @test all(vecA .== Int(5))
end

@testset "command queue batching" begin
    function increment_kernel(A)
        A[1] = A[1] + Int32(1)
        return
    end

    function write_kernel(A, value)
        A[1] = value
        return
    end

    queue = global_queue(device())
    A = MtlArray(Int32[0])
    synchronize(queue)

    for _ in 1:8
        @metal threads=1 queue=queue increment_kernel(A)
    end
    if !Metal.command_batching() || Metal.profiling_command_buffers()
        @test queue.cmdbuf === nothing
    elseif Metal.command_batch_max_ops() > 1
        @test queue.nops == 8
    end
    synchronize(queue)
    @test Array(A) == Int32[8]
    @test queue.cmdbuf === nothing

    @metal threads=1 queue=queue submit=true increment_kernel(A)
    @test queue.cmdbuf === nothing
    synchronize(queue)
    @test Array(A) == Int32[9]

    B = MtlArray(Int32[0])
    Metal.unsafe_copyto!(device(B), pointer(B), pointer(A), 1; queue, async=true)
    @metal threads=1 queue=queue increment_kernel(B)
    synchronize(queue)
    @test Array(B) == Int32[10]

    C = MtlArray{UInt8}(undef, 4)
    Metal.unsafe_fill!(device(C), pointer(C), UInt8(3), length(C); queue, async=true)
    synchronize(queue)
    @test Array(C) == fill(UInt8(3), 4)

    D = MtlArray(UInt8[0])
    @metal threads=1 queue=queue write_kernel(D, UInt8(1))
    cmdbuf = MTL.MTLCommandBuffer(queue)
    if !Metal.command_batching() || Metal.profiling_command_buffers()
        @test queue.cmdbuf === nothing
    elseif Metal.command_batch_max_ops() > 1
        @test queue.nops == 1
    end
    @metal threads=1 queue=queue write_kernel(D, UInt8(2))
    MTL.MTLBlitCommandEncoder(cmdbuf) do enc
        buf = Base.unsafe_convert(MTL.MTLBuffer, D)
        MTL.append_fillbuffer!(enc, buf, UInt8(3), sizeof(D), D.offset)
    end
    MTL.commit!(cmdbuf)
    synchronize(queue)
    @test Array(D) == UInt8[3]
end

@testset "kernel launch cleanup" begin
    function scalar_arg_kernel(A, val)
        A[1] = val
        return
    end

    A = MtlArray{Int32}(undef, 1)
    kernel = @metal launch=false scalar_arg_kernel(A, Int32(1))

    kernel(A, Int32(1))
    synchronize()

    stats0 = copy(Metal.alloc_stats)
    kernel(A, Int32(2))
    synchronize()
    stats1 = copy(Metal.alloc_stats)
    diff = stats1 - stats0

    @test Array(A) == Int32[2]
    @test diff.alloc_count == diff.free_count
    @test diff.alloc_bytes == diff.free_bytes
end

@testset "device synchronization" begin
    t = @async begin
        @metal threads=(bufferSize) tester(bufferA)
    end
    wait(t)
    device_synchronize()
    @test all(vecA .== Int(5))
end

@testset "device-side exceptions" begin
    # a device exception must not wedge the GPU (JuliaGPU/Metal.jl#433); it should
    # complete cleanly and surface to the host as a `KernelException` on synchronize.
    function throwing_kernel(a)
        a[2] = 1f0      # out-of-bounds store on a length-1 array
        return
    end
    function fill_one(a)
        a[thread_position_in_grid_1d()] = 1f0
        return
    end

    a = Metal.zeros(Float32, 1)
    @metal threads=1 throwing_kernel(a)
    @test_throws Metal.KernelException synchronize()

    # the faulting lane's position is recorded at debug level >= 2 (the recording machinery
    # slows down every kernel that can throw, even when nothing ever does; see
    # `claim_output!`)
    function throw_at_three(a)
        if thread_position_in_threadgroup().x == 3
            a[2] = 1f0  # out-of-bounds store on a length-1 array
        end
        return
    end
    @metal threads=4 debug_level=2 throw_at_three(a)
    exc = try
        synchronize()
        nothing
    catch err
        err
    end
    @test exc isa Metal.KernelException
    @test exc.thread == (3, 1, 1)
    @test exc.threadgroup == (1, 1, 1)
    @test exc.name == "BoundsError"
    @test exc.reason == "Out-of-bounds array access"

    # the mailbox is reset on read, and the GPU stays usable afterwards
    b = Metal.zeros(Float32, 4)
    @metal threads=4 fill_one(b)
    synchronize()
    @test Array(b) == ones(Float32, 4)
end

@testset "exception reporting per debug level" begin
    # `@metal debug_level=` controls how much an exception reports, independent of the
    # session's `-g` (it's part of the compile cache key, resolved at codegen), so all three
    # tiers can be checked in one process regardless of how the suite was launched.
    bounds_oob(a) = (a[2] = 1f0; return)   # out-of-bounds on a length-1 array
    nonquirk(out, d) = (out[1] = 1 ÷ d[1]; return)   # divide-by-zero -> throw(DivideError())
    function throw_at(dl, kernel, args...)
        @metal threads=1 debug_level=dl kernel(args...)
        try; synchronize(); nothing; catch err; err; end
    end

    # -g0: only that an exception occurred; everything else stays at its sentinel
    exc0 = throw_at(0, bounds_oob, Metal.zeros(Float32, 1))
    @test exc0 isa Metal.KernelException
    @test isempty(exc0.name)
    @test isempty(exc0.reason)
    @test exc0.thread == (0, 0, 0)
    @test isempty(exc0.backtrace)

    # -g1: the faulting type and reason for quirk throws; no position (the recording
    # machinery slows down every kernel that can throw, even when nothing ever does;
    # see `claim_output!`)
    exc1 = throw_at(1, bounds_oob, Metal.zeros(Float32, 1))
    @test exc1.name == "BoundsError"
    @test exc1.reason == "Out-of-bounds array access"
    @test exc1.thread == (0, 0, 0)
    @test isempty(exc1.backtrace)

    # a non-quirk throw records the compiler-deduced type name (here `jl_throw`'s generic
    # "exception") only at debug level >= 2: copying that runtime string takes a byte loop
    # on the unhappy path, which is similarly penalized (see `report_exception`)
    excn = throw_at(1, nonquirk, Metal.zeros(Int32, 1), MtlArray(Int32[0]))
    @test excn isa Metal.KernelException
    @test isempty(excn.name)
    excn2 = throw_at(2, nonquirk, Metal.zeros(Int32, 1), MtlArray(Int32[0]))
    @test excn2.name == "exception"

    # -g2: adds the faulting position and the device stack trace
    exc2 = throw_at(2, bounds_oob, Metal.zeros(Float32, 1))
    @test exc2.name == "BoundsError"
    @test exc2.thread == (1, 1, 1)
    @test exc2.threadgroup == (1, 1, 1)
    @test !isempty(exc2.backtrace)
    @test any(frame -> occursin("throw_boundserror", frame[1]), exc2.backtrace)
end

@testset "launch params" begin
    vecA .= 0
    @metal threads=(2) tester(bufferA)
    synchronize()
    @test all(vecA == Int.([5, 5, 0, 0, 0, 0, 0, 0]))
    vecA .= 0

    @metal groups=(3) threads=(2) tester(bufferA)
    synchronize()
    @test all(vecA == Int.([5, 5, 5, 5, 5, 5, 0, 0]))
    vecA .= 0

    dev = device()
    queue = MTL.MTLCommandQueue(dev)
    @metal threads=(3) queue=queue tester(bufferA)
    synchronize(queue)
    @test all(vecA == Int.([5, 5, 5, 0, 0, 0, 0, 0]))
    vecA .= 0

    @test_throws InexactError @metal threads=(-2) tester(bufferA)
    @test_throws InexactError @metal groups=(-2) tester(bufferA)
    @test_throws ArgumentError @metal threads=(1025) tester(bufferA)
    @test_throws ArgumentError @metal threads=(1000,2) tester(bufferA)

    @test_throws ArgumentError @metal threads=(1024,1,1) groups=(4194304,1,1) tester(bufferA)
    @test_throws ArgumentError @metal threads=(1,1024,1) groups=(1,4194304,1) tester(bufferA)
    @test_throws ArgumentError @metal threads=(1,1,1024) groups=(1,1,4194304) tester(bufferA)
end

############################################################################################

@testset "argument passing" begin
    @testset "buffer argument" begin
        function kernel(ptr)
            unsafe_store!(ptr, 42)
            return
        end

        a = MtlArray([1])
        @metal kernel(pointer(a))
        @test Array(a)[] == 42
    end

    @testset "scalar argument" begin
        function kernel(ptr, val)
            unsafe_store!(ptr, val)
            return
        end

        a = MtlArray([1])
        @metal kernel(pointer(a), 42)
        @test Array(a)[] == 42
    end

    @testset "array argument" begin
        function kernel(ptr, vals)
            unsafe_store!(ptr, vals[1])
            return
        end

        a = MtlArray([1])
        @metal kernel(pointer(a), (42,))
        @test Array(a)[] == 42
    end

    @testset "struct argument" begin
        function kernel(ptr, vals)
            unsafe_store!(ptr, vals[1] + vals[2])
            return
        end

        a = MtlArray([1])
        @metal kernel(pointer(a), (20, Int32(22)))
        @test Array(a)[] == 42
    end

    @testset "indirect struct argument" begin
        function kernel(obj)
            unsafe_store!(obj[1], obj[2])
            return
        end

        a = MtlArray([1])
        @metal kernel((pointer(a), 42))
        @test Array(a)[] == 42
    end

    @testset "nested indirect struct argument" begin
        function kernel(obj)
            unsafe_store!(obj[1][1], obj[2])
            return
        end

        a = MtlArray([1])
        @metal kernel(((pointer(a), 0), 42))
        @test Array(a)[] == 42
    end

    @testset "array in struct argument" begin
        function kernel(obj)
            unsafe_store!(obj[1], obj[2][1]+obj[2][2])
            return
        end

        a = MtlArray([1])
        @metal kernel((pointer(a), (20,22)))
        @test Array(a)[] == 42
    end

    @testset "unused mutable types" begin
        function kernel(T, ptr)
            unsafe_store!(ptr, one(T))
            return
        end

        a = MtlArray([0])
        @metal kernel(Int, pointer(a))
        @test Array(a)[] == 1
    end
end
