[Metal]
# which storage mode unspecified allocations should default to.
# possible values: "private", "shared", "managed"
#default_storage = "private"

# when false, always use metal 3 even on a metal 4 platform
#force_metal3 = false
