steps:
  - label: ":julia: Run segfaulting tests"
    plugins:
      - JuliaCI/julia#v1: ~
      - JuliaCI/coreupload#v2:
          core_pattern: "*.core"
          compressor: "zstd"
          create_bundle: "true"
          lldb_commands:
            - "thread backtrace all"
    commands: |
      julia -e 'ccall(:abort, Nothing, ())'
    agents:
      queue: "juliatest"
      os: "macos"
      arch: "aarch64"
