steps:
  - label: ":julia: Run segfaulting tests"
    plugins:
      - JuliaCI/julia#43d54223e61fcb856c3b480a95b1a709a99744b8: ~
      - JuliaCI/coreupload#v1:
          core_pattern: "*.core"
          compressor: "zstd"
          create_bundle: "true"
          gdb_commands:
            - "thread apply all bt"
            - "info file"
    commands: |
      julia -e 'ccall(:abort, Nothing, ())'
    agents:
      queue: "juliatest"
      os: "macos"
      arch: "aarch64"
