steps:
  # Julia versions
  - group: ":julia: Julia"
    key: "julia"
    steps:
      - label: "Julia {{matrix.julia}}"
        plugins:
          - JuliaCI/julia#v1:
              version: "{{matrix.julia}}"
          - JuliaCI/julia-test#v1:
              test_args: "--quickfail"
          - JuliaCI/julia-coverage#v1:
              codecov: true
              dirs:
                - src
                - lib
        agents:
          queue: "juliaecosystem"
          os: "macos"
          arch: "aarch64"
        if: |
          build.message =~ /\[only tests\]/ ||
          build.message =~ /\[only julia\]/ ||
          build.message !~ /\[only/ &&
            build.message !~ /\[skip tests\]/ &&
            build.message !~ /\[skip julia\]/
        timeout_in_minutes: 60
        matrix:
          setup:
            julia:
              - "1.10"
              - "1.11"
              - "1.12"

  - group: ":soon: Pre-releases"
    steps:
      - label: "Julia pre-release {{matrix.julia}}"
        plugins:
          - JuliaCI/julia#v1:
              version: "{{matrix.julia}}"
          - JuliaCI/julia-test#v1:
              test_args: "--quickfail"
          - JuliaCI/julia-coverage#v1:
              codecov: true
              dirs:
                - src
                - lib
        agents:
          queue: "juliaecosystem"
          os: "macos"
          arch: "aarch64"
        if: |
          build.message =~ /\[only tests\]/ ||
          build.message =~ /\[only pre\]/ ||
          build.message !~ /\[only/ &&
            build.message !~ /\[skip tests\]/ &&
            build.message !~ /\[skip pre\]/
        timeout_in_minutes: 30
        soft_fail: true
        matrix:
          setup:
            julia:
              - "1.13-nightly"
              # - "nightly" # uncomment once dependencies support current llvm

  # special tests
  - group: ":eyes: Special"
    depends_on: "julia"
    steps:
      - label: ":floppy_disk: Shared Storage"
        plugins:
          - JuliaCI/julia#v1:
              version: "1.12"
          - JuliaCI/julia-test#v1:
              test_args: "--quickfail"
        agents:
          queue: "juliaecosystem"
          os: "macos"
          arch: "aarch64"
        if: |
          build.message =~ /\[only tests\]/ ||
          build.message =~ /\[only special\]/ ||
          build.message !~ /\[only/ && !build.pull_request.draft &&
            build.message !~ /\[skip tests\]/ &&
            build.message !~ /\[skip special\]/
        timeout_in_minutes: 60
        commands: |
          echo -e "[Metal]\ndefault_storage = \"shared\"" >LocalPreferences.toml
      - label: ":mag: API validation"
        plugins:
          - JuliaCI/julia#v1:
              version: "1.12"
          - JuliaCI/julia-test#v1:
              # test_args: "--quickfail"
              test_args: ""
              # Don't quickfail to see which ones fail
          - JuliaCI/julia-coverage#v1:
              codecov: true
              dirs:
                - src
                - lib
        env:
          MTL_DEBUG_LAYER: '1'
          MTL_SHADER_VALIDATION: '1'
        commands: |
          # blocking synchronization is easier to validate
          echo -e "[Metal]\nnonblocking_synchronization = false" >LocalPreferences.toml
        agents:
          queue: "juliaecosystem"
          os: "macos"
          arch: "aarch64"
          macos_version: "15.0"
        if: |
          build.message =~ /\[only tests\]/ ||
          build.message =~ /\[only validation\]/ ||
          build.message =~ /\[only special\]/ ||
          build.message !~ /\[only/ && !build.pull_request.draft &&
            build.message !~ /\[skip tests\]/ &&
            build.message !~ /\[skip validation\]/ &&
            build.message !~ /\[skip special\]/
        timeout_in_minutes: 60
      # - label: ":ram: Large buffers"
      #   plugins:
      #     - JuliaCI/julia#v1:
      #         version: "1.12"
      #     - JuliaCI/julia-test#v1:
      #         test_args: "--jobs=1 --quickfail largecopy largebroadcast"
      #     - JuliaCI/julia-coverage#v1:
      #         codecov: true
      #         dirs:
      #           - src
      #           - lib
      #   env:
      #     MTL_DEBUG_LAYER: '1'
      #     MTL_SHADER_VALIDATION: '1'
      #   agents:
      #     queue: "juliaecosystem"
      #     os: "macos"
      #     arch: "aarch64"
      #     macos_version: "15.0"
      #   if: |
      #     build.message =~ /\[only tests\]/ ||
      #     build.message =~ /\[only large\]/ ||
      #     build.message =~ /\[only special\]/ ||
      #     build.message !~ /\[only/ && !build.pull_request.draft &&
      #       build.message !~ /\[skip tests\]/ &&
      #       build.message !~ /\[skip large\]/ &&
      #       build.message !~ /\[skip special\]/
      #   timeout_in_minutes: 15

  - wait: ~
    continue_on_failure: true

  - label: ":racehorse: Benchmarks"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.12"
    command: |
      echo "--- :git: Setting up worktrees"
      git fetch -q origin 356e7d28ea5c2005aa3bd51ab3a3389cc28ad135
      git fetch -q origin ab6b7a3d104cb4d7dbd87d00a2e66594656feaf6
      git worktree add worktree-before 356e7d28ea5c2005aa3bd51ab3a3389cc28ad135
      git worktree add worktree-fix ab6b7a3d104cb4d7dbd87d00a2e66594656feaf6

      echo "--- :julia: Instantiating projects"
      julia --project=envs/before -e 'using Pkg; Pkg.develop(path="worktree-before"); Pkg.add("BenchmarkTools"); Pkg.status()'
      julia --project=envs/after -e 'using Pkg; Pkg.develop(path=pwd()); Pkg.add("BenchmarkTools"); Pkg.status()'
      julia --project=envs/fix -e 'using Pkg; Pkg.develop(path="worktree-fix"); Pkg.add("BenchmarkTools"); Pkg.status()'

      echo "+++ :racehorse: BEFORE 796, -g1"
      julia --project=envs/before perf/mwe796.jl
      echo "+++ :racehorse: AFTER 796, -g1"
      julia --project=envs/after perf/mwe796.jl
      echo "+++ :racehorse: FIX tb/fix_796_regression, -g1"
      julia --project=envs/fix perf/mwe796.jl
      echo "+++ :racehorse: FIX tb/fix_796_regression, -g2"
      julia -g2 --project=envs/fix perf/mwe796.jl
    agents:
      queue: "juliaecosystem"
      os: "macos"
      arch: "aarch64"
    if: |
      build.message =~ /\[only benchmarks\]/ ||
      build.message !~ /\[only/ && !build.pull_request.draft &&
        build.message !~ /\[skip benchmarks\]/
    timeout_in_minutes: 30
