steps:
  # Julia versions
  - group: ":julia: Julia"
    key: "julia"
    steps:
      - label: "Julia {{matrix.julia}}"
        plugins:
          - JuliaCI/external-buildkite#20760554f2386037ab61f930ccd4637280153bfc:
              version: './buildkite.version'
              repo_url: 'https://github.com/JuliaCI/julia-buildkite.git'
              folder: '.buildkite2'
        agents:
          queue: "juliatest"
          os: "macos"
          arch: "aarch64"
        matrix:
          setup:
            julia:
              - "1.10"
