steps:
  # Julia versions
  - group: ":julia: Julia"
    key: "julia"
    steps:
      - label: "Julia 1.8"
        plugins:
          - JuliaCI/julia#v1:
              version: 1.8
          - JuliaCI/julia-test#v1:
              test_args: "--quickfail"
          - JuliaCI/julia-coverage#v1:
              codecov: true
              dirs:
                - src
                - lib
                - examples
        command: |
          julia --project=deps deps/build_ci.jl
        agents:
          queue: "juliaecosystem"
          os: "macos"
          arch: "aarch64"
          macos_version: "13.2"
        if: build.message !~ /\[skip tests\]/
        timeout_in_minutes: 60

      - label: "Julia 1.9"
        plugins:
          - JuliaCI/julia#v1:
              version: 1.9-nightly
         - JuliaCI/julia-test#v1:
             test_args: "--quickfail"
          - JuliaCI/julia-coverage#v1:
              codecov: true
              dirs:
                - src
                - lib
                - examples
        command: |
          julia --project=deps deps/build_ci.jl
        agents:
          queue: "juliaecosystem"
          os: "macos"
          arch: "aarch64"
          macos_version: "13.2"
        if: build.message !~ /\[skip tests\]/ && !build.pull_request.draft
        timeout_in_minutes: 60

      # - label: "Julia nightly"
      #   plugins:
      #     - JuliaCI/julia#v1:
      #         version: nightly
      #     - JuliaCI/julia-test#v1:
      #         test_args: "--quickfail"
      #     - JuliaCI/julia-coverage#v1:
      #         codecov: true
      #         dirs:
      #           - src
      #           - lib
      #           - examples
      #   command: |
      #     julia --project=deps deps/build_ci.jl
      #   agents:
      #     queue: "juliaecosystem"
      #     os: "macos"
      #     arch: "aarch64"
      #   if: build.message !~ /\[skip tests\]/ && !build.pull_request.draft
      #   timeout_in_minutes: 60
      #   soft_fail:
      #     - exit_status: 1

  # special tests
  - group: ":eyes: Special"
    depends_on: "julia"
    steps:
      - label: "Metal API Validation"
        plugins:
          - JuliaCI/julia#v1:
              version: 1.8
          - JuliaCI/julia-test#v1:
              test_args: "--quickfail metal"
              # only enabled for select tests due to JuliaGPU/Metal.jl#34
          - JuliaCI/julia-coverage#v1:
              codecov: true
              dirs:
                - src
                - lib
                - examples
        command: |
          julia --project=deps deps/build_ci.jl
        env:
          MTL_DEBUG_LAYER: '1'
          MTL_SHADER_VALIDATION: '1'
        agents:
          queue: "juliaecosystem"
          os: "macos"
          arch: "aarch64"
        if: build.message !~ /\[skip tests\]/ && !build.pull_request.draft
        timeout_in_minutes: 60
