steps:
  # Julia versions
  - group: ":julia: Julia"
    key: "julia"
    steps:
      - label: "Julia {{matrix.julia}}"
        plugins:
          - JuliaCI/julia#v1:
              version: "{{matrix.julia}}"
          - JuliaCI/julia-test#v1:
              test_args: "--quickfail"
          - JuliaCI/julia-coverage#v1:
              codecov: true
              dirs:
                - src
                - lib
                - examples
        agents:
          queue: "juliaecosystem"
          os: "macos"
          arch: "aarch64"
        if: build.message !~ /\[skip tests\]/
        timeout_in_minutes: 60
        matrix:
          setup:
            julia:
              - "1.10"
              - "1.11"
              - "nightly"
          adjustments:
            - with:
                julia: "nightly"
              soft_fail: true

  # special tests
  - group: ":eyes: Special"
    depends_on: "julia"
    steps:
      - label: "macOS 15"
        plugins:
          - JuliaCI/julia#v1:
              version: "1.10"
          - JuliaCI/julia-test#v1:
              test_args: "--quickfail"
        agents:
          queue: "julia"
          os: "macos"
          arch: "aarch64"
          macos_version: "15.0"
        if: build.message !~ /\[skip tests\]/ && !build.pull_request.draft
        timeout_in_minutes: 60
      - label: "{{matrix.storage}} array storage"
        plugins:
          - JuliaCI/julia#v1:
              version: "1.10"
          - JuliaCI/julia-test#v1:
              test_args: "--quickfail"
        agents:
          queue: "juliaecosystem"
          os: "macos"
          arch: "aarch64"
        if: build.message !~ /\[skip tests\]/ && !build.pull_request.draft
        timeout_in_minutes: 60
        matrix:
          setup:
            storage:
              - "shared"
              - "managed"
        commands: |
          echo -e "[Metal]\ndefault_storage = \"{{matrix.storage}}\"" > LocalPreferences.toml
      - label: "API validation"
        plugins:
          - JuliaCI/julia#v1:
              version: "1.10"
          - JuliaCI/julia-test#v1:
              test_args: "--quickfail metal"
              # only enabled for select tests due to JuliaGPU/Metal.jl#34
          - JuliaCI/julia-coverage#v1:
              codecov: true
              dirs:
                - src
                - lib
                - examples
        env:
          MTL_DEBUG_LAYER: '1'
          MTL_SHADER_VALIDATION: '1'
        agents:
          queue: "juliaecosystem"
          os: "macos"
          arch: "aarch64"
        if: build.message !~ /\[skip tests\]/ && !build.pull_request.draft
        timeout_in_minutes: 60
      - label: "Opaque pointers"
        plugins:
          - JuliaCI/julia#v1:
              version: "1.10"
          - JuliaCI/julia-test#v1:
              test_args: "--quickfail"
          - JuliaCI/julia-coverage#v1:
              codecov: true
              dirs:
                - src
                - lib
                - examples
        env:
          JULIA_LLVM_ARGS: '--opaque-pointers'
        agents:
          queue: "juliaecosystem"
          os: "macos"
          arch: "aarch64"
        if: build.message !~ /\[skip tests\]/ && !build.pull_request.draft
        timeout_in_minutes: 60
