# This file is automatically generated. Do not edit!
# To re-generate, execute res/wrap/wrap.jl

using CEnum: CEnum, @cenum

const MPSGraphCallableMap = NSDictionary

const MPSGraphTensorDataDictionary = NSDictionary


@objcwrapper immutable = true availability = macos(v"14.0.0") MPSGraphObject <: NSObject

@objcwrapper immutable = true MPSGraphType <: MPSGraphObject

@objcwrapper immutable = true MPSGraphShapedType <: MPSGraphType

@objcproperties MPSGraphShapedType begin
    @autoproperty shape::id{MPSShape} setter = setShape
    @autoproperty dataType::MPSDataType setter = setDataType
end

@cenum MPSGraphTensorNamedDataLayout::UInt64 begin
    MPSGraphTensorNamedDataLayoutNCHW = 0x0000000000000000
    MPSGraphTensorNamedDataLayoutNHWC = 0x0000000000000001
    MPSGraphTensorNamedDataLayoutOIHW = 0x0000000000000002
    MPSGraphTensorNamedDataLayoutHWIO = 0x0000000000000003
    MPSGraphTensorNamedDataLayoutCHW = 0x0000000000000004
    MPSGraphTensorNamedDataLayoutHWC = 0x0000000000000005
    MPSGraphTensorNamedDataLayoutHW = 0x0000000000000006
    MPSGraphTensorNamedDataLayoutNCDHW = 0x0000000000000007
    MPSGraphTensorNamedDataLayoutNDHWC = 0x0000000000000008
    MPSGraphTensorNamedDataLayoutOIDHW = 0x0000000000000009
    MPSGraphTensorNamedDataLayoutDHWIO = 0x000000000000000a
end

@cenum MPSGraphPaddingStyle::UInt64 begin
    MPSGraphPaddingStyleExplicit = 0x0000000000000000
    MPSGraphPaddingStyleTF_VALID = 0x0000000000000001
    MPSGraphPaddingStyleTF_SAME = 0x0000000000000002
    MPSGraphPaddingStyleExplicitOffset = 0x0000000000000003
    MPSGraphPaddingStyleONNX_SAME_LOWER = 0x0000000000000004
end

@cenum MPSGraphPaddingMode::Int64 begin
    MPSGraphPaddingModeConstant = 0
    MPSGraphPaddingModeReflect = 1
    MPSGraphPaddingModeSymmetric = 2
    MPSGraphPaddingModeClampToEdge = 3
    MPSGraphPaddingModeZero = 4
    MPSGraphPaddingModePeriodic = 5
    MPSGraphPaddingModeAntiPeriodic = 6
end

@cenum MPSGraphReductionMode::UInt64 begin
    MPSGraphReductionModeMin = 0x0000000000000000
    MPSGraphReductionModeMax = 0x0000000000000001
    MPSGraphReductionModeSum = 0x0000000000000002
    MPSGraphReductionModeProduct = 0x0000000000000003
    MPSGraphReductionModeArgumentMin = 0x0000000000000004
    MPSGraphReductionModeArgumentMax = 0x0000000000000005
end

@cenum MPSGraphDeviceType::UInt32 begin
    MPSGraphDeviceTypeMetal = 0x0000000000000000
end

@objcwrapper immutable = true MPSGraphDevice <: MPSGraphObject

@objcproperties MPSGraphDevice begin
    @autoproperty type::MPSGraphDeviceType
    @autoproperty metalDevice::id{MTLDevice}
end

@cenum MPSGraphOptions::UInt64 begin
    MPSGraphOptionsNone = 0x0000000000000000
    MPSGraphOptionsSynchronizeResults = 0x0000000000000001
    MPSGraphOptionsVerbose = 0x0000000000000002
    MPSGraphOptionsDefault = 0x0000000000000001
end

@objcwrapper immutable = true MPSGraph <: MPSGraphObject

@objcproperties MPSGraph begin
    @autoproperty options::MPSGraphOptions setter = setOptions
    @autoproperty placeholderTensors::id{NSArray} type = Vector{MPSGraphTensor}
end

@objcwrapper immutable = true MPSGraphOperation <: MPSGraphObject

@objcproperties MPSGraphOperation begin
    @autoproperty inputTensors::id{NSArray} type = Vector{MPSGraphTensor}
    @autoproperty outputTensors::id{NSArray} type = Vector{MPSGraphTensor}
    @autoproperty controlDependencies::id{NSArray} type = Vector{MPSGraphOperation}
    @autoproperty graph::id{MPSGraph}
    @autoproperty name::id{NSString}
end

@objcwrapper immutable = true MPSGraphTensor <: MPSGraphObject

@objcproperties MPSGraphTensor begin
    @autoproperty shape::id{MPSShape}
    @autoproperty dataType::MPSDataType
    @autoproperty operation::id{MPSGraphOperation}
end

@objcwrapper immutable = false MPSGraphTensorData <: MPSGraphObject

@objcproperties MPSGraphTensorData begin
    @autoproperty shape::id{MPSShape}
    @autoproperty dataType::MPSDataType
    @autoproperty device::id{MPSGraphDevice}
end

@cenum MPSGraphOptimization::UInt64 begin
    MPSGraphOptimizationLevel0 = 0x0000000000000000
    MPSGraphOptimizationLevel1 = 0x0000000000000001
end

@cenum MPSGraphOptimizationProfile::UInt64 begin
    MPSGraphOptimizationProfilePerformance = 0x0000000000000000
    MPSGraphOptimizationProfilePowerEfficiency = 0x0000000000000001
end

@cenum MPSGraphExecutionStage::UInt64 begin
    MPSGraphExecutionStageCompleted = 0x0000000000000000
end

@objcwrapper immutable = true MPSGraphCompilationDescriptor <: MPSGraphObject

@objcproperties MPSGraphCompilationDescriptor begin
    @autoproperty optimizationLevel::MPSGraphOptimization setter = setOptimizationLevel
    @autoproperty waitForCompilationCompletion::Bool setter = setWaitForCompilationCompletion
    #= setter = setCompilationCompletionHandler:Skipping property compilationCompletionHandler because it is a CLBlockPointer void (^)(MPSGraphExecutable *, NSError *) =#
    @autoproperty dispatchQueue::id{dispatch_queue_t} setter = setDispatchQueue
    @autoproperty optimizationProfile::MPSGraphOptimizationProfile setter = setOptimizationProfile
    @autoproperty callables::id{MPSGraphCallableMap} setter = setCallables availability = macos(v"14.1.0")
end

@objcwrapper immutable = true MPSGraphExecutionDescriptor <: MPSGraphObject

@objcproperties MPSGraphExecutionDescriptor begin
    #= setter = setScheduledHandler:Skipping property scheduledHandler because it is a CLBlockPointer void (^)(NSDictionary<MPSGraphTensor *,MPSGraphTensorData *> *, NSError *) =#
    #= setter = setCompletionHandler:Skipping property completionHandler because it is a CLBlockPointer void (^)(NSDictionary<MPSGraphTensor *,MPSGraphTensorData *> *, NSError *) =#
    @autoproperty waitUntilCompleted::Bool setter = setWaitUntilCompleted
    @autoproperty compilationDescriptor::id{MPSGraphCompilationDescriptor} setter = setCompilationDescriptor
end

@objcwrapper immutable = true MPSGraphExecutableExecutionDescriptor <: MPSGraphObject

@objcproperties MPSGraphExecutableExecutionDescriptor begin
    #= setter = setScheduledHandler:Skipping property scheduledHandler because it is a CLBlockPointer void (^)(NSArray<MPSGraphTensorData *> *, NSError *) =#
    #= setter = setCompletionHandler:Skipping property completionHandler because it is a CLBlockPointer void (^)(NSArray<MPSGraphTensorData *> *, NSError *) =#
    @autoproperty waitUntilCompleted::Bool setter = setWaitUntilCompleted
end

@cenum MPSGraphDeploymentPlatform::UInt64 begin
    MPSGraphDeploymentPlatformMacOS = 0x0000000000000000
    MPSGraphDeploymentPlatformIOS = 0x0000000000000001
    MPSGraphDeploymentPlatformTvOS = 0x0000000000000002
    MPSGraphDeploymentPlatformVisionOS = 0x0000000000000003
end

@objcwrapper immutable = true availability = macos(v"14.0.0") MPSGraphExecutableSerializationDescriptor <: MPSGraphObject

@objcproperties MPSGraphExecutableSerializationDescriptor begin
    @autoproperty append::Bool setter = setAppend
    @autoproperty deploymentPlatform::MPSGraphDeploymentPlatform setter = setDeploymentPlatform
    @autoproperty minimumDeploymentTarget::id{NSString} setter = setMinimumDeploymentTarget
end

@objcwrapper immutable = true MPSGraphExecutable <: MPSGraphObject

@objcproperties MPSGraphExecutable begin
    @autoproperty options::MPSGraphOptions setter = setOptions
    @autoproperty feedTensors::id{NSArray} type = Vector{MPSGraphTensor}
    @autoproperty targetTensors::id{NSArray} type = Vector{MPSGraphTensor}
end

@objcwrapper immutable = true MPSGraphConvolution2DOpDescriptor <: MPSGraphObject

@objcproperties MPSGraphConvolution2DOpDescriptor begin
    @autoproperty strideInX::UInt64 setter = setStrideInX
    @autoproperty strideInY::UInt64 setter = setStrideInY
    @autoproperty dilationRateInX::UInt64 setter = setDilationRateInX
    @autoproperty dilationRateInY::UInt64 setter = setDilationRateInY
    @autoproperty paddingLeft::UInt64 setter = setPaddingLeft
    @autoproperty paddingRight::UInt64 setter = setPaddingRight
    @autoproperty paddingTop::UInt64 setter = setPaddingTop
    @autoproperty paddingBottom::UInt64 setter = setPaddingBottom
    @autoproperty paddingStyle::MPSGraphPaddingStyle setter = setPaddingStyle
    @autoproperty dataLayout::MPSGraphTensorNamedDataLayout setter = setDataLayout
    @autoproperty weightsLayout::MPSGraphTensorNamedDataLayout setter = setWeightsLayout
    @autoproperty groups::UInt64 setter = setGroups
end

@objcwrapper immutable = true availability = macos(v"13.2.0") MPSGraphConvolution3DOpDescriptor <: MPSGraphObject

@objcproperties MPSGraphConvolution3DOpDescriptor begin
    @autoproperty strideInX::UInt64 setter = setStrideInX
    @autoproperty strideInY::UInt64 setter = setStrideInY
    @autoproperty strideInZ::UInt64 setter = setStrideInZ
    @autoproperty dilationRateInX::UInt64 setter = setDilationRateInX
    @autoproperty dilationRateInY::UInt64 setter = setDilationRateInY
    @autoproperty dilationRateInZ::UInt64 setter = setDilationRateInZ
    @autoproperty paddingLeft::UInt64 setter = setPaddingLeft
    @autoproperty paddingRight::UInt64 setter = setPaddingRight
    @autoproperty paddingTop::UInt64 setter = setPaddingTop
    @autoproperty paddingBottom::UInt64 setter = setPaddingBottom
    @autoproperty paddingFront::UInt64 setter = setPaddingFront
    @autoproperty paddingBack::UInt64 setter = setPaddingBack
    @autoproperty paddingStyle::MPSGraphPaddingStyle setter = setPaddingStyle
    @autoproperty dataLayout::MPSGraphTensorNamedDataLayout setter = setDataLayout
    @autoproperty weightsLayout::MPSGraphTensorNamedDataLayout setter = setWeightsLayout
    @autoproperty groups::UInt64 setter = setGroups
end

@objcwrapper immutable = true MPSGraphDepthwiseConvolution2DOpDescriptor <: MPSGraphObject

@objcproperties MPSGraphDepthwiseConvolution2DOpDescriptor begin
    @autoproperty strideInX::UInt64 setter = setStrideInX
    @autoproperty strideInY::UInt64 setter = setStrideInY
    @autoproperty dilationRateInX::UInt64 setter = setDilationRateInX
    @autoproperty dilationRateInY::UInt64 setter = setDilationRateInY
    @autoproperty paddingLeft::UInt64 setter = setPaddingLeft
    @autoproperty paddingRight::UInt64 setter = setPaddingRight
    @autoproperty paddingTop::UInt64 setter = setPaddingTop
    @autoproperty paddingBottom::UInt64 setter = setPaddingBottom
    @autoproperty paddingStyle::MPSGraphPaddingStyle setter = setPaddingStyle
    @autoproperty dataLayout::MPSGraphTensorNamedDataLayout setter = setDataLayout
    @autoproperty weightsLayout::MPSGraphTensorNamedDataLayout setter = setWeightsLayout
end

@objcwrapper immutable = true MPSGraphDepthwiseConvolution3DOpDescriptor <: MPSGraphObject

@objcproperties MPSGraphDepthwiseConvolution3DOpDescriptor begin
    @autoproperty strides::id{NSArray} type = Vector{NSNumber} setter = setStrides
    @autoproperty dilationRates::id{NSArray} type = Vector{NSNumber} setter = setDilationRates
    @autoproperty paddingValues::id{NSArray} type = Vector{NSNumber} setter = setPaddingValues
    @autoproperty paddingStyle::MPSGraphPaddingStyle setter = setPaddingStyle
    @autoproperty channelDimensionIndex::Int64 setter = setChannelDimensionIndex
end

@cenum MPSGraphFFTScalingMode::UInt64 begin
    MPSGraphFFTScalingModeNone = 0x0000000000000000
    MPSGraphFFTScalingModeSize = 0x0000000000000001
    MPSGraphFFTScalingModeUnitary = 0x0000000000000002
end

@objcwrapper immutable = true availability = macos(v"14.0.0") MPSGraphFFTDescriptor <: MPSGraphObject

@objcproperties MPSGraphFFTDescriptor begin
    @autoproperty inverse::Bool setter = setInverse
    @autoproperty scalingMode::MPSGraphFFTScalingMode setter = setScalingMode
    @autoproperty roundToOddHermitean::Bool setter = setRoundToOddHermitean
end

@objcwrapper immutable = true availability = macos(v"14.0.0") MPSGraphImToColOpDescriptor <: MPSGraphObject

@objcproperties MPSGraphImToColOpDescriptor begin
    @autoproperty kernelWidth::UInt64 setter = setKernelWidth
    @autoproperty kernelHeight::UInt64 setter = setKernelHeight
    @autoproperty strideInX::UInt64 setter = setStrideInX
    @autoproperty strideInY::UInt64 setter = setStrideInY
    @autoproperty dilationRateInX::UInt64 setter = setDilationRateInX
    @autoproperty dilationRateInY::UInt64 setter = setDilationRateInY
    @autoproperty paddingLeft::UInt64 setter = setPaddingLeft
    @autoproperty paddingRight::UInt64 setter = setPaddingRight
    @autoproperty paddingTop::UInt64 setter = setPaddingTop
    @autoproperty paddingBottom::UInt64 setter = setPaddingBottom
    @autoproperty dataLayout::MPSGraphTensorNamedDataLayout setter = setDataLayout
end

@cenum MPSGraphLossReductionType::UInt64 begin
    MPSGraphLossReductionTypeNone = 0x0000000000000000
    MPSGraphLossReductionTypeAxis = 0x0000000000000000
    MPSGraphLossReductionTypeSum = 0x0000000000000001
    MPSGraphLossReductionTypeMean = 0x0000000000000002
end

@objcwrapper immutable = true MPSGraphVariableOp <: MPSGraphOperation

@objcproperties MPSGraphVariableOp begin
    @autoproperty shape::id{MPSShape}
    @autoproperty dataType::MPSDataType
end

@cenum MPSGraphNonMaximumSuppressionCoordinateMode::UInt64 begin
    MPSGraphNonMaximumSuppressionCoordinateModeCornersHeightFirst = 0x0000000000000000
    MPSGraphNonMaximumSuppressionCoordinateModeCornersWidthFirst = 0x0000000000000001
    MPSGraphNonMaximumSuppressionCoordinateModeCentersHeightFirst = 0x0000000000000002
    MPSGraphNonMaximumSuppressionCoordinateModeCentersWidthFirst = 0x0000000000000003
end

@cenum MPSGraphPoolingReturnIndicesMode::UInt64 begin
    MPSGraphPoolingReturnIndicesNone = 0x0000000000000000
    MPSGraphPoolingReturnIndicesGlobalFlatten1D = 0x0000000000000001
    MPSGraphPoolingReturnIndicesGlobalFlatten2D = 0x0000000000000002
    MPSGraphPoolingReturnIndicesGlobalFlatten3D = 0x0000000000000003
    MPSGraphPoolingReturnIndicesGlobalFlatten4D = 0x0000000000000004
    MPSGraphPoolingReturnIndicesLocalFlatten1D = 0x0000000000000005
    MPSGraphPoolingReturnIndicesLocalFlatten2D = 0x0000000000000006
    MPSGraphPoolingReturnIndicesLocalFlatten3D = 0x0000000000000007
    MPSGraphPoolingReturnIndicesLocalFlatten4D = 0x0000000000000008
end

@objcwrapper immutable = true MPSGraphPooling2DOpDescriptor <: MPSGraphObject

@objcproperties MPSGraphPooling2DOpDescriptor begin
    @autoproperty kernelWidth::UInt64 setter = setKernelWidth
    @autoproperty kernelHeight::UInt64 setter = setKernelHeight
    @autoproperty strideInX::UInt64 setter = setStrideInX
    @autoproperty strideInY::UInt64 setter = setStrideInY
    @autoproperty dilationRateInX::UInt64 setter = setDilationRateInX
    @autoproperty dilationRateInY::UInt64 setter = setDilationRateInY
    @autoproperty paddingLeft::UInt64 setter = setPaddingLeft
    @autoproperty paddingRight::UInt64 setter = setPaddingRight
    @autoproperty paddingTop::UInt64 setter = setPaddingTop
    @autoproperty paddingBottom::UInt64 setter = setPaddingBottom
    @autoproperty paddingStyle::MPSGraphPaddingStyle setter = setPaddingStyle
    @autoproperty dataLayout::MPSGraphTensorNamedDataLayout setter = setDataLayout
    @autoproperty returnIndicesMode::MPSGraphPoolingReturnIndicesMode setter = setReturnIndicesMode
    @autoproperty returnIndicesDataType::MPSDataType setter = setReturnIndicesDataType
    @autoproperty ceilMode::Bool setter = setCeilMode
    @autoproperty includeZeroPadToAverage::Bool setter = setIncludeZeroPadToAverage
end

@objcwrapper immutable = true MPSGraphPooling4DOpDescriptor <: MPSGraphObject

@objcproperties MPSGraphPooling4DOpDescriptor begin
    @autoproperty kernelSizes::id{NSArray} type = Vector{NSNumber} setter = setKernelSizes
    @autoproperty strides::id{NSArray} type = Vector{NSNumber} setter = setStrides
    @autoproperty dilationRates::id{NSArray} type = Vector{NSNumber} setter = setDilationRates
    @autoproperty paddingValues::id{NSArray} type = Vector{NSNumber} setter = setPaddingValues
    @autoproperty paddingStyle::MPSGraphPaddingStyle setter = setPaddingStyle
    @autoproperty ceilMode::Bool setter = setCeilMode
    @autoproperty includeZeroPadToAverage::Bool setter = setIncludeZeroPadToAverage
    @autoproperty returnIndicesMode::MPSGraphPoolingReturnIndicesMode setter = setReturnIndicesMode
    @autoproperty returnIndicesDataType::MPSDataType setter = setReturnIndicesDataType
end

@cenum MPSGraphRandomDistribution::UInt64 begin
    MPSGraphRandomDistributionUniform = 0x0000000000000000
    MPSGraphRandomDistributionNormal = 0x0000000000000001
    MPSGraphRandomDistributionTruncatedNormal = 0x0000000000000002
end

@cenum MPSGraphRandomNormalSamplingMethod::UInt64 begin
    MPSGraphRandomNormalSamplingInvCDF = 0x0000000000000000
    MPSGraphRandomNormalSamplingBoxMuller = 0x0000000000000001
end

@objcwrapper immutable = true MPSGraphRandomOpDescriptor <: MPSGraphObject

@objcproperties MPSGraphRandomOpDescriptor begin
    @autoproperty distribution::MPSGraphRandomDistribution setter = setDistribution
    @autoproperty dataType::MPSDataType setter = setDataType
    @autoproperty min::Cfloat setter = setMin
    @autoproperty max::Cfloat setter = setMax
    @autoproperty minInteger::Int64 setter = setMinInteger
    @autoproperty maxInteger::Int64 setter = setMaxInteger
    @autoproperty mean::Cfloat setter = setMean
    @autoproperty standardDeviation::Cfloat setter = setStandardDeviation
    @autoproperty samplingMethod::MPSGraphRandomNormalSamplingMethod setter = setSamplingMethod
end

@cenum MPSGraphResizeMode::UInt64 begin
    MPSGraphResizeNearest = 0x0000000000000000
    MPSGraphResizeBilinear = 0x0000000000000001
end

@cenum MPSGraphResizeNearestRoundingMode::UInt64 begin
    MPSGraphResizeNearestRoundingModeRoundPreferCeil = 0x0000000000000000
    MPSGraphResizeNearestRoundingModeRoundPreferFloor = 0x0000000000000001
    MPSGraphResizeNearestRoundingModeCeil = 0x0000000000000002
    MPSGraphResizeNearestRoundingModeFloor = 0x0000000000000003
    MPSGraphResizeNearestRoundingModeRoundToEven = 0x0000000000000004
    MPSGraphResizeNearestRoundingModeRoundToOdd = 0x0000000000000005
end

@cenum MPSGraphRNNActivation::UInt64 begin
    MPSGraphRNNActivationNone = 0x0000000000000000
    MPSGraphRNNActivationRelu = 0x0000000000000001
    MPSGraphRNNActivationTanh = 0x0000000000000002
    MPSGraphRNNActivationSigmoid = 0x0000000000000003
    MPSGraphRNNActivationHardSigmoid = 0x0000000000000004
end

@objcwrapper immutable = true MPSGraphSingleGateRNNDescriptor <: MPSGraphObject

@objcproperties MPSGraphSingleGateRNNDescriptor begin
    @autoproperty reverse::Bool setter = setReverse
    @autoproperty bidirectional::Bool setter = setBidirectional
    @autoproperty training::Bool setter = setTraining
    @autoproperty activation::MPSGraphRNNActivation setter = setActivation
end

@objcwrapper immutable = true MPSGraphLSTMDescriptor <: MPSGraphObject

@objcproperties MPSGraphLSTMDescriptor begin
    @autoproperty reverse::Bool setter = setReverse
    @autoproperty bidirectional::Bool setter = setBidirectional
    @autoproperty produceCell::Bool setter = setProduceCell
    @autoproperty training::Bool setter = setTraining
    @autoproperty forgetGateLast::Bool setter = setForgetGateLast
    @autoproperty inputGateActivation::MPSGraphRNNActivation setter = setInputGateActivation
    @autoproperty forgetGateActivation::MPSGraphRNNActivation setter = setForgetGateActivation
    @autoproperty cellGateActivation::MPSGraphRNNActivation setter = setCellGateActivation
    @autoproperty outputGateActivation::MPSGraphRNNActivation setter = setOutputGateActivation
    @autoproperty activation::MPSGraphRNNActivation setter = setActivation
end

@objcwrapper immutable = true MPSGraphGRUDescriptor <: MPSGraphObject

@objcproperties MPSGraphGRUDescriptor begin
    @autoproperty reverse::Bool setter = setReverse
    @autoproperty bidirectional::Bool setter = setBidirectional
    @autoproperty training::Bool setter = setTraining
    @autoproperty resetGateFirst::Bool setter = setResetGateFirst
    @autoproperty resetAfter::Bool setter = setResetAfter
    @autoproperty flipZ::Bool setter = setFlipZ
    @autoproperty updateGateActivation::MPSGraphRNNActivation setter = setUpdateGateActivation
    @autoproperty resetGateActivation::MPSGraphRNNActivation setter = setResetGateActivation
    @autoproperty outputGateActivation::MPSGraphRNNActivation setter = setOutputGateActivation
end

@cenum MPSGraphScatterMode::Int64 begin
    MPSGraphScatterModeAdd = 0
    MPSGraphScatterModeSub = 1
    MPSGraphScatterModeMul = 2
    MPSGraphScatterModeDiv = 3
    MPSGraphScatterModeMin = 4
    MPSGraphScatterModeMax = 5
    MPSGraphScatterModeSet = 6
end

@cenum MPSGraphSparseStorageType::UInt64 begin
    MPSGraphSparseStorageCOO = 0x0000000000000000
    MPSGraphSparseStorageCSC = 0x0000000000000001
    MPSGraphSparseStorageCSR = 0x0000000000000002
end

@objcwrapper immutable = true MPSGraphCreateSparseOpDescriptor <: MPSGraphObject

@objcproperties MPSGraphCreateSparseOpDescriptor begin
    @autoproperty sparseStorageType::MPSGraphSparseStorageType setter = setSparseStorageType
    @autoproperty dataType::MPSDataType setter = setDataType
end

@objcwrapper immutable = true MPSGraphStencilOpDescriptor <: MPSGraphObject

@objcproperties MPSGraphStencilOpDescriptor begin
    @autoproperty reductionMode::MPSGraphReductionMode setter = setReductionMode
    @autoproperty offsets::id{MPSShape} setter = setOffsets
    @autoproperty strides::id{MPSShape} setter = setStrides
    @autoproperty dilationRates::id{MPSShape} setter = setDilationRates
    @autoproperty explicitPadding::id{MPSShape} setter = setExplicitPadding
    @autoproperty boundaryMode::MPSGraphPaddingMode setter = setBoundaryMode
    @autoproperty paddingStyle::MPSGraphPaddingStyle setter = setPaddingStyle
    @autoproperty paddingConstant::Cfloat setter = setPaddingConstant
end
