[general]
library_name = "Symbol(\"/System/Library/Frameworks/Metal.framework/Resources/BridgeSupport/Metal.dylib\")"
output_file_path = "../../lib/mtl/libmtl.jl"

minimum_macos_supported = "13"

generate_isystem_symbols = false

printer_blacklist = [
    "mt_macCatalyst",
    "mt_ios",
    "mt_macos",
    "CF*",

    # Temporarily disable MTLFunctionLog because
    # "function" property breaks formatter
    "MTLFunctionLog",
]

[codegen]
use_ccall_macro = true
always_NUL_terminated_string = true
opaque_as_mutable_struct = true

[codegen.macro]
# it's highly recommended to set this entry to "basic".
# if you'd like to skip all of the macros, please set this entry to "disable".
# if you'd like to translate function-like macros to Julia, please set this entry to "aggressive".
macro_mode = "disable"

# API
# Adjustments to the expressions done by the rewriter in wrap.jl
# Sorted in alphabetical order. For more info on the options, see
# the comment in wrap.jl
[api.MTLBinaryArchive]
immutable=false

[api.MTLBinaryArchiveDescriptor]
immutable=false

[api.MTLBuffer.proptype]
gpuAddress="Ptr{Cvoid}"

[api.MTLCaptureDescriptor]
immutable=false

[api.MTLCommandBufferDescriptor]
immutable=false

[api.MTLCommandQueue]
immutable=false

[api.MTLCompileOptions]
immutable=false
    [api.MTLCompileOptions.proptype]
    languageVersion="VersionNumber"

[api.MTLComputeCommandEncoder]
immutable=false

[api.MTLComputePipelineDescriptor]
immutable=false

[api.MTLComputePipelineState]
immutable=false

[api.MTLEvent]
immutable=false

[api.MTLFence]
immutable=false

[api.MTLFunction]
immutable=false

[api.MTLFunctionDescriptor]
immutable=false

[api.MTLHeap]
immutable=false

[api.MTLHeapDescriptor]
immutable=false

[api.MTLLibrary]
immutable=false

[api.MTLSharedEvent]
immutable=false

[api.MTLTexture]
immutable=false

[api.MTLTextureDescriptor]
immutable=false
