[general]
library_name = "libmtl"
output_file_path = "../../lib/mtl/libmtl.jl"
prologue_file_path = "libmtl_prologue.jl"

generate_isystem_symbols = false

printer_blacklist = [
    "mt_macCatalyst",
    "mt_ios",
    "mt_macos",
    "CF*",

    # Temporarily disable MTLFunctionLog because
    # "function" property breaks formatter
    "MTLFunctionLog",
]

[codegen]
minimum_macos_supported = "14"
use_ccall_macro = true
always_NUL_terminated_string = true
opaque_as_mutable_struct = true

[codegen.macro]
# it's highly recommended to set this entry to "basic".
# if you'd like to skip all of the macros, please set this entry to "disable".
# if you'd like to translate function-like macros to Julia, please set this entry to "aggressive".
macro_mode = "disable"

# API
# Adjustments to the expressions done by the rewriter in wrap.jl
# Sorted in alphabetical order. For more info on the options, see
# the comment in wrap.jl
[api.MTLBinaryArchive]
managed=true

[api.MTLBinaryArchiveDescriptor]
managed=true

[api.MTLBuffer.proptype]
gpuAddress="Ptr{Cvoid}"

[api.MTLCaptureDescriptor]
managed=true

[api.MTLCommandBufferDescriptor]
managed=true

[api.MTLCommandQueue]
managed=true

[api.MTLCommandQueueDescriptor]
managed=true

[api.MTL4CommandQueueDescriptor]
managed=true

[api.MTL4CommandQueue]
managed=true

[api.MTL4CommitOptions]
managed=true

[api.MTLCompileOptions]
managed=true
    [api.MTLCompileOptions.proptype]
    languageVersion="VersionNumber"

[api.MTL4ComputeCommandEncoder]
managed=true

[api.MTL4CommandAllocatorDescriptor]
managed=true

[api.MTL4CommandAllocator]
managed=true

[api.MTLComputePipelineDescriptor]
managed=true

[api.MTLComputePipelineState]
managed=true

[api.MTLEvent]
managed=true

[api.MTLSharedEventHandle]
managed=true

[api.MTLFence]
managed=true

[api.MTLFunction]
managed=true

[api.MTLFunctionDescriptor]
managed=true

[api.MTL4FunctionDescriptor]
managed=true

[api.MTLHeap]
managed=true

[api.MTLHeapDescriptor]
managed=true

[api.MTLLibrary]
managed=true

[api.MTLLogStateDescriptor]
managed=true

[api.MTLResidencySet]
managed=true

[api.MTLSharedEvent]
managed=true

[api.MTLTexture]
managed=true

[api.MTLTextureDescriptor]
managed=true
