[general]
library_name = "libmps"
output_file_path = "../../lib/mps/libmps.jl"
prologue_file_path = "libmps_prologue.jl"

minimum_macos_supported = "13"

printer_blacklist = [
    "mt_macCatalyst",
    "mt_ios",
    "mt_macos",
    "CF.*",
    "MTL.*",
    "NS.*",
    "BOOL",
    # Not sure how to access the MPS functions so don't wrap for now
    "MPSDataTypeBitsCount",
    "MPSSizeofMPSDataType",
    "MPSSizeofMPSDataType",
    "MPSFindIntegerDivisionParams",
    "MPSGetCustomKernelMaxBatchSize",
    "MPSGetCustomKernelBatchedDestinationIndex",
    "MPSGetCustomKernelBatchedSourceIndex",
    "MPSGetCustomKernelBroadcastSourceIndex",
    # NSKeyedUnarchiver not defined
    "MPSKeyedUnarchiver",
    "MPS.*AccelerationStructure.*", # All deprecated
    # "MPSHandle",
    #"MPSCNNConvolutionDataSource",
    "MPSImageTransformProvider",
]

[codegen]
use_ccall_macro = true
always_NUL_terminated_string = true
opaque_as_mutable_struct = true

version_function = "Metal.is_macos"

[codegen.macro]
# it's highly recommended to set this entry to "basic".
# if you'd like to skip all of the macros, please set this entry to "disable".
# if you'd like to translate function-like macros to Julia, please set this entry to "aggressive".
macro_mode = "disable"

[api.immutable]
MPSMatrixCopy=false
MPSMatrixDecompositionLU=false
MPSMatrixDecompositionCholesky=false
MPSUnaryImageKernel=false
MPSBinaryImageKernel=false
MPSImageGaussianBlur=false
MPSImageBox=false
MPSMatrixUnaryKernel=false
MPSMatrixBinaryKernel=false
MPSMatrix=false
MPSMatrixMultiplication=false
MPSMatrixFindTopK=false
MPSMatrixSoftMax=false
MPSMatrixLogSoftMax=false
MPSMatrixRandomDistributionDescriptor=false
MPSMatrixRandom=false
MPSMatrixRandomMTGP32=false
MPSMatrixRandomPhilox=false
MPSNDArrayDescriptor=false
MPSNDArray=false
MPSTemporaryNDArray=false
MPSNDArrayMultiaryBase=false
MPSNDArrayMultiaryKernel=false
MPSNDArrayUnaryKernel=false
MPSNDArrayBinaryKernel=false
MPSNDArrayMatrixMultiplication=false
MPSVector=false
MPSTemporaryVector=false
MPSMatrixVectorMultiplication=false

[api.override_supertype]
MPSCommandBuffer="MTLCommandBuffer"
MPSHandle="NSObject"

[api.constructor]
MPSRegion = "MPSRegion(origin=MPSOrigin(), size=MPSSize()) = new(origin, size)"
MPSOrigin = "MPSOrigin(x=0.0, y=0.0, z=0.0) = new(x, y, z)"
MPSOffset = "MPSOffset(x=0, y=0, z=0) = new(x, y, z)"
MPSSize = "MPSSize(w=1.0, h=1.0, d=1.0) = new(w, h, d)"
