[general]
library_name = "Symbol(\"/System/Library/Frameworks/Metal.framework/Resources/BridgeSupport/Metal.dylib\")"
output_file_path = "../../lib/mtl/libmtl.jl"
prologue_file_path = "libmtl_prologue.jl"

minimum_macos_supported = "13"

generate_isystem_symbols = false

printer_blacklist = [
    "mt_macCatalyst",
    "mt_ios",
    "mt_macos",
    "CF*",

    # Temporarily disable MTLFunctionLog because
    # "function" property breaks formatter
    "MTLFunctionLog",
    # Don't print because dispatch_queue_t ??
    "MTLSharedEventListener",
]

[codegen]
use_ccall_macro = true
always_NUL_terminated_string = true
opaque_as_mutable_struct = true

version_function = "Metal.macos_version()"

[codegen.macro]
# it's highly recommended to set this entry to "basic".
# if you'd like to skip all of the macros, please set this entry to "disable".
# if you'd like to translate function-like macros to Julia, please set this entry to "aggressive".
macro_mode = "disable"

[api.immutable]
MTLTextureDescriptor=false
MTLLibrary=false
MTLHeap=false
MTLHeapDescriptor=false
MTLFunction=false
MTLFunctionDescriptor=false
MTLFence=false
MTLEvent=false
MTLSharedEvent=false
MTLComputePipelineDescriptor=false
MTLComputePipelineState=false
MTLCompileOptions=false
MTLCommandQueue=false
MTLCommandBufferDescriptor=false
MTLBinaryArchive=false
MTLBinaryArchiveDescriptor=false
MTLCaptureDescriptor=false
MTLComputeCommandEncoder=false
MTLTexture=false


[api.constructor]
MTLRegion = "MTLRegion(origin=MTLOrigin(), size=MTLSize()) = new(origin, size)"
MTLSize = "MTLSize(w=1, h=1, d=1) = new(w, h, d)"
MTLOrigin = "MTLOrigin(x=0, y=0, z=0) = new(x, y, z)"
