[general]
library_name = "libmps"
output_file_path = "../../lib/mps/libmps.jl"
prologue_file_path = "libmps_prologue.jl"

minimum_macos_supported = "13"

printer_blacklist = [
    "mt_macCatalyst",
    "mt_ios",
    "mt_macos",
    "CF.*",
    "MTL.*",
    "NS.*",
    "BOOL",
    # Not sure how to access the MPS functions so don't wrap for now
    "MPSDataTypeBitsCount",
    "MPSSizeofMPSDataType",
    "MPSSizeofMPSDataType",
    "MPSFindIntegerDivisionParams",
    "MPSGetCustomKernelMaxBatchSize",
    "MPSGetCustomKernelBatchedDestinationIndex",
    "MPSGetCustomKernelBatchedSourceIndex",
    "MPSGetCustomKernelBroadcastSourceIndex",
    # NSKeyedUnarchiver not defined
    "MPSKeyedUnarchiver",
    "MPS.*AccelerationStructure.*", # All deprecated
    # "MPSHandle",
    #"MPSCNNConvolutionDataSource",
    "MPSImageTransformProvider",
]

[codegen]
use_ccall_macro = true
always_NUL_terminated_string = true
opaque_as_mutable_struct = true

[codegen.macro]
# it's highly recommended to set this entry to "basic".
# if you'd like to skip all of the macros, please set this entry to "disable".
# if you'd like to translate function-like macros to Julia, please set this entry to "aggressive".
macro_mode = "disable"


# API
# Adjustments to the expressions done by the rewriter in wrap.jl
# Sorted in alphabetical order. For more info on the options, see
# the comment in wrap.jl
[api.MPSBinaryImageKernel]
immutable=false

[api.MPSCommandBuffer]
supertype="MTLCommandBuffer"

[api.MPSHandle]
supertype="NSObject"

[api.MPSImageBox]
immutable=false

[api.MPSImageGaussianBlur]
immutable=false

[api.MPSMatrix]
immutable=false

[api.MPSMatrixBinaryKernel]
immutable=false

[api.MPSMatrixCopy]
immutable=false

[api.MPSMatrixDecompositionCholesky]
immutable=false

[api.MPSMatrixDecompositionLU]
immutable=false

[api.MPSMatrixFindTopK]
immutable=false

[api.MPSMatrixLogSoftMax]
immutable=false

[api.MPSMatrixMultiplication]
immutable=false

[api.MPSMatrixRandom]
immutable=false

[api.MPSMatrixRandomDistributionDescriptor]
immutable=false

[api.MPSMatrixRandomMTGP32]
immutable=false

[api.MPSMatrixRandomPhilox]
immutable=false

[api.MPSMatrixSoftMax]
immutable=false

[api.MPSMatrixUnaryKernel]
immutable=false

[api.MPSMatrixVectorMultiplication]
immutable=false

[api.MPSNDArray]
immutable=false

[api.MPSNDArrayBinaryKernel]
immutable=false

[api.MPSNDArrayDescriptor]
immutable=false

[api.MPSNDArrayMatrixMultiplication]
immutable=false

[api.MPSNDArrayMultiaryBase]
immutable=false

[api.MPSNDArrayMultiaryKernel]
immutable=false

[api.MPSNDArrayUnaryKernel]
immutable=false

[api.MPSTemporaryNDArray]
immutable=false

[api.MPSTemporaryVector]
immutable=false

[api.MPSUnaryImageKernel]
immutable=false

[api.MPSVector]
immutable=false
