[general]
library_name = "Symbol(\"/System/Library/Frameworks/Metal.framework/Resources/BridgeSupport/Metal.dylib\")"
output_file_path = "../../lib/mtl/libmtl.jl"
prologue_file_path = "libmtl_prologue.jl"

minimum_macos_supported = "13"

generate_isystem_symbols = false

printer_blacklist = [
    "mt_macCatalyst",
    "mt_ios",
    "mt_macos",
    "CF*",

    # Temporarily disable MTLFunctionLog because
    # "function" property breaks formatter
    "MTLFunctionLog",
    # Don't print because dispatch_queue_t ??
    "MTLSharedEventListener",
]

[codegen]
use_ccall_macro = true
always_NUL_terminated_string = true

version_function = "Metal.macos_version()"

[codegen.macro]
# it's highly recommended to set this entry to "basic".
# if you'd like to skip all of the macros, please set this entry to "disable".
# if you'd like to translate function-like macros to Julia, please set this entry to "aggressive".
macro_mode = "disable"

[api.MTLTextureDescriptor]
immutable=false

[api.MTLLibrary]
immutable=false

[api.MTLHeap]
immutable=false

[api.MTLHeapDescriptor]
immutable=false

[api.MTLFunction]
immutable=false

[api.MTLFunctionDescriptor]
immutable=false

[api.MTLFence]
immutable=false

[api.MTLEvent]
immutable=false

[api.MTLSharedEvent]
immutable=false

[api.MTLComputePipelineDescriptor]
immutable=false

[api.MTLComputePipelineState]
immutable=false

[api.MTLCompileOptions]
immutable=false

[api.MTLCommandQueue]
immutable=false

[api.MTLCommandBufferDescriptor]
immutable=false

[api.MTLBinaryArchive]
immutable=false

[api.MTLBinaryArchiveDescriptor]
immutable=false

[api.MTLCaptureDescriptor]
immutable=false

[api.MTLComputeCommandEncoder]
immutable=false

[api.MTLTexture]
immutable=false


[api.MTLSize]
constructor = "MTLSize(w=1, h=1, d=1) = new(w, h, d)"

[api.MTLRegion]
constructor = "MTLRegion(origin=MTLOrigin(), size=MTLSize()) = new(origin, size)"

[api.MTLOrigin]
constructor = "MTLOrigin(x=0, y=0, z=0) = new(x, y, z)"
