[general]
library_name = "libmps"
output_file_path = "../../lib/mps/libmps.jl"
prologue_file_path = "libmps_prologue.jl"

minimum_macos_supported = "13"

printer_blacklist = [
    "mt_macCatalyst",
    "mt_ios",
    "mt_macos",
    "CF.*",
    "MTL.*",
    "NS.*",
    "BOOL",
    # Not sure how to access the MPS functions so don't wrap for now
    "MPSDataTypeBitsCount",
    "MPSSizeofMPSDataType",
    "MPSSizeofMPSDataType",
    "MPSFindIntegerDivisionParams",
    "MPSGetCustomKernelMaxBatchSize",
    "MPSGetCustomKernelBatchedDestinationIndex",
    "MPSGetCustomKernelBatchedSourceIndex",
    "MPSGetCustomKernelBroadcastSourceIndex",
    # NSKeyedUnarchiver not defined
    "MPSKeyedUnarchiver",
    "MPSHandle",
    "MPSCNNConvolutionDataSource",
    "MPSImageTransformProvider",
]

[codegen]
use_ccall_macro = true
always_NUL_terminated_string = true

version_function = "Metal.macos_version()"

[codegen.macro]
# it's highly recommended to set this entry to "basic".
# if you'd like to skip all of the macros, please set this entry to "disable".
# if you'd like to translate function-like macros to Julia, please set this entry to "aggressive".
macro_mode = "disable"

[api.MPSMatrixCopy]
immutable=false

[api.MPSMatrixDecompositionLU]
immutable=false

[api.MPSMatrixDecompositionCholesky]
immutable=false

[api.MPSUnaryImageKernel]
immutable=false

[api.MPSBinaryImageKernel]
immutable=false

[api.MPSImageGaussianBlur]
immutable=false

[api.MPSImageBox]
immutable=false

[api.MPSMatrixUnaryKernel]
immutable=false

[api.MPSMatrixBinaryKernel]
immutable=false

[api.MPSMatrix]
immutable=false

[api.MPSMatrixMultiplication]
immutable=false

[api.MPSMatrixFindTopK]
immutable=false

[api.MPSMatrixSoftMax]
immutable=false

[api.MPSMatrixLogSoftMax]
immutable=false

[api.MPSMatrixRandomDistributionDescriptor]
immutable=false

[api.MPSMatrixRandom]
immutable=false

[api.MPSMatrixRandomMTGP32]
immutable=false

[api.MPSMatrixRandomPhilox]
immutable=false

[api.MPSNDArrayDescriptor]
immutable=false

[api.MPSNDArray]
immutable=false

[api.MPSTemporaryNDArray]
immutable=false

[api.MPSNDArrayMultiaryBase]
immutable=false

[api.MPSNDArrayMultiaryKernel]
immutable=false

[api.MPSNDArrayUnaryKernel]
immutable=false

[api.MPSNDArrayBinaryKernel]
immutable=false

[api.MPSNDArrayMatrixMultiplication]
immutable=false

[api.MPSVector]
immutable=false

[api.MPSTemporaryVector]
immutable=false

[api.MPSCommandBuffer]
override_supertype="MTLCommandBuffer"

[api.MPSMatrixVectorMultiplication]
immutable=false

[api.MPSSize]
constructor = "MPSSize(w=1.0, h=1.0, d=1.0) = new(w, h, d)"

[api.MPSRegion]
constructor = "MPSRegion(origin=MPSOrigin(), size=MPSSize()) = new(origin, size)"

[api.MPSOrigin]
constructor = "MPSOrigin(x=0.0, y=0.0, z=0.0) = new(x, y, z)"

[api.MPSOffset]
constructor = "MPSOffset(x=0, y=0, z=0) = new(x, y, z)"
