name: Load

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - main
    tags: '*'

permissions:
  contents: read

  # needed for julia-actions/cache to delete old caches
  actions: write

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} (load)
    runs-on: ${{ matrix.os }}
    if: github.event.pull_request.draft == false
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1'
        os:
          - 'ubuntu-latest'
          - 'macOS-14'
          - 'macOS-15-intel'
          - 'macOS-26-intel'
          - 'windows-latest'

    steps:
      - uses: actions/checkout@v6
      - uses: julia-actions/setup-julia@v3
        with:
          version: ${{ matrix.version }}
          arch: 'default'

      - uses: julia-actions/cache@v3
      - uses: julia-actions/julia-buildpkg@v1

      - name: Test that Metal loads but is not functional
        shell: julia --color=yes --project=. {0}
        run: |
          using Metal
          @assert Metal.functional() == false "Metal.functional() should report false on unsupported platforms"
